### ISSUE TITLE
Incorrect usage examples, missing package name

### ISSUE THREAD

**Issue by BlackHawkPL** [unitedoperations/orbats#1]
https://github.com/unitedoperations/orbats/blob/de758d72701822b5325c53cc8cd8ac99f6da85a2/US/Viet_Air_Cav_PLT/gear.sqf#L3-L10

**Comment by callensm** [comment]
Ah yes, I tend to do that for my COOPs to avoid having to write loadout extensions. Will fix.

**Comment by callensm** [comment]
The previous commit addressed the lack of package definition and closes #1
